"""initial_schema

Revision ID: 69f0bc910814
Revises: 
Create Date: 2026-03-03 03:00:14.553917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f0bc910814'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('commission_override', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealer_bonuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('threshold_min', sa.Integer(), nullable=False),
    sa.Column('threshold_max', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealer_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_on', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dealerships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('google_place_id', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True),
    sa.Column('subscription_status', sa.String(length=32), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('tag', sa.String(length=24), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=False),
    sa.Column('stock_num', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('new_used', sa.String(length=16), nullable=False),
    sa.Column('deal_type', sa.String(length=32), nullable=False),
    sa.Column('business_manager', sa.String(length=80), nullable=False),
    sa.Column('spot_sold', sa.Boolean(), nullable=False),
    sa.Column('discount_gt_200', sa.Boolean(), nullable=False),
    sa.Column('aim_presentation', sa.String(length=3), nullable=False),
    sa.Column('permaplate', sa.Boolean(), nullable=False),
    sa.Column('nitro_fill', sa.Boolean(), nullable=False),
    sa.Column('pulse', sa.Boolean(), nullable=False),
    sa.Column('finance_non_subvented', sa.Boolean(), nullable=False),
    sa.Column('warranty', sa.Boolean(), nullable=False),
    sa.Column('tire_wheel', sa.Boolean(), nullable=False),
    sa.Column('hold_amount', sa.Float(), nullable=False),
    sa.Column('aim_amount', sa.Float(), nullable=False),
    sa.Column('fi_pvr', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('unit_comm', sa.Float(), nullable=False),
    sa.Column('add_ons', sa.Float(), nullable=False),
    sa.Column('trade_hold_comm', sa.Float(), nullable=False),
    sa.Column('total_deal_comm', sa.Float(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.String(length=64), nullable=True),
    sa.Column('commission_override', sa.Float(), nullable=True),
    sa.Column('front_gross', sa.Float(), nullable=False),
    sa.Column('back_gross', sa.Float(), nullable=False),
    sa.Column('expected_commission', sa.Float(), nullable=False),
    sa.Column('actual_paid', sa.Float(), nullable=True),
    sa.Column('on_delivery_board', sa.Boolean(), nullable=False),
    sa.Column('gas_ready', sa.Boolean(), nullable=False),
    sa.Column('inspection_ready', sa.Boolean(), nullable=False),
    sa.Column('insurance_ready', sa.Boolean(), nullable=False),
    sa.Column('split_deal', sa.Boolean(), nullable=False),
    sa.Column('star_car', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('unit_goal', sa.Integer(), nullable=False),
    sa.Column('commission_goal', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_token'), 'invites', ['token'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_upvotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('post_type', sa.String(length=16), nullable=False),
    sa.Column('anonymity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('unit_comm_discount_le_200', sa.Float(), nullable=False),
    sa.Column('unit_comm_discount_gt_200', sa.Float(), nullable=False),
    sa.Column('permaplate', sa.Float(), nullable=False),
    sa.Column('nitro_fill', sa.Float(), nullable=False),
    sa.Column('pulse', sa.Float(), nullable=False),
    sa.Column('finance_non_subvented', sa.Float(), nullable=False),
    sa.Column('warranty', sa.Float(), nullable=False),
    sa.Column('tire_wheel', sa.Float(), nullable=False),
    sa.Column('hourly_rate_ny_offset', sa.Float(), nullable=False),
    sa.Column('new_volume_bonus_15_16', sa.Float(), nullable=False),
    sa.Column('new_volume_bonus_17_18', sa.Float(), nullable=False),
    sa.Column('new_volume_bonus_19_20', sa.Float(), nullable=False),
    sa.Column('new_volume_bonus_21_24', sa.Float(), nullable=False),
    sa.Column('new_volume_bonus_25_plus', sa.Float(), nullable=False),
    sa.Column('used_volume_bonus_8_10', sa.Float(), nullable=False),
    sa.Column('used_volume_bonus_11_12', sa.Float(), nullable=False),
    sa.Column('used_volume_bonus_13_plus', sa.Float(), nullable=False),
    sa.Column('spot_bonus_5_9', sa.Float(), nullable=False),
    sa.Column('spot_bonus_10_12', sa.Float(), nullable=False),
    sa.Column('spot_bonus_13_plus', sa.Float(), nullable=False),
    sa.Column('quarterly_bonus_threshold_units', sa.Integer(), nullable=False),
    sa.Column('quarterly_bonus_amount', sa.Float(), nullable=False),
    sa.Column('pay_type', sa.String(length=16), nullable=False),
    sa.Column('gross_front_pct', sa.Float(), nullable=False),
    sa.Column('gross_back_pct', sa.Float(), nullable=False),
    sa.Column('mini_deal', sa.Float(), nullable=False),
    sa.Column('pack_deduction', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('supabase_id', sa.String(length=64), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('dealership_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_community_visit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('supabase_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('settings')
    op.drop_table('reminders')
    op.drop_table('posts')
    op.drop_table('post_upvotes')
    op.drop_table('poll_votes')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_invites_token'), table_name='invites')
    op.drop_table('invites')
    op.drop_table('goals')
    op.drop_table('deals')
    op.drop_table('dealerships')
    op.drop_table('dealer_products')
    op.drop_table('dealer_bonuses')
    op.drop_table('deal_products')
    # ### end Alembic commands ###
